name: amplify_storage_plugin_interface
description: The Amplify Flutter Storage category plugin interface.
version: 0.0.1
homepage: https://github.com/aws-amplify/amplify-flutter/tree/master/packages/amplify_storage_plugin_interface

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
