sdk:
  - '2.17.0'
  - stable
  - dev

stages:
  - analyze_and_format:
      - group:
          - format
          - analyze: --fatal-infos .
  - unit_test:
      - test:
      - command: dart run build_runner test -- -p chrome
      - command: dart run build_runner test --release -- -p chrome
