name: amplify_analytics_pinpoint
description: A new flutter plugin project.
version: 0.0.1
homepage: https://github.com/aws-amplify/amplify-flutter/tree/master/packages/amplify_analytics_pinpoint

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter
  amplify_analytics_plugin_interface:
    path: ../amplify_analytics_plugin_interface
  plugin_platform_interface: ^1.0.1
  # amplify_core included only for testing: should be removed after pub.dev up and running
  amplify_core:
    path: ../amplify_core

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.amazonaws.amplify.amplify_analytics_pinpoint
        pluginClass: AmplifyAnalyticsPinpointPlugin
      ios:
        pluginClass: AmplifyAnalyticsPinpointPlugin
