name: cognito_example
description: Amplify Auth Cognito for Dart example
version: 1.0.0
publish_to: none

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  amplify_auth_cognito_dart: ">=0.6.0 <0.7.0"
  amplify_core: ">=1.0.0-next.5 <1.0.0-next.6"
  amplify_secure_storage_dart: ">=0.1.4+2 <0.2.0"
  example_common:
    path: ../../../example_common

dependency_overrides:
  amplify_api_dart:
    path: ../../../api/amplify_api_dart
  amplify_core:
    path: ../../../amplify_core
  amplify_secure_storage_dart:
    path: ../../../secure_storage/amplify_secure_storage_dart
  aws_common:
    path: ../../../aws_common
  aws_signature_v4:
    path: ../../../aws_signature_v4
  worker_bee:
    path: ../../../worker_bee/worker_bee

dev_dependencies:
  amplify_api_dart: ^0.1.0
  amplify_lints:
    path: ../../../amplify_lints
  amplify_test:
  browser_launcher: ^1.1.1
  build_runner: ^2.1.4
  build_web_compilers: ^3.2.1
  checks: ^0.2.0
  cli_script: ^0.3.0
  io: ^1.0.0
  mime: ^1.0.0
  path: ^1.8.0
  shelf: ^1.4.0
  shelf_web_socket: ^1.0.3
  stream_channel: ^2.1.1
  test: ^1.22.0
  webdriver: ^3.0.0
